name: Daily YouTube Upload

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install --upgrade pip
        pip install edge-tts
        pip install moviepy==1.0.3
        pip install requests
        pip install google-auth-oauthlib
        pip install google-api-python-client
        pip install pillow

    - name: Run script
      env:
        PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: python main.py
